stages:
  [ 'linting', 'refactoring', 'test' ]

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip3 install -r flake8.txt
    - flake8 --verbose .

black:
  stage: refactoring
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

test:
  stage: test
  image: python:3.11
  script:
    - pip3 install -r requirements/test.txt
    - cd lyceum
    - python3 manage.py test