stages:
  [ 'linting', 'refactoring', 'test' ]

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip3 install flake8-quotes==3.4.0
    - pip3 install pep8-naming==0.14.1
    - pip3 install flake8-import-order==0.18.2
    - pip3 install flake8-commas==4.0.0
    - pip3 install flake8-dunder-all==0.4.1
    - pip3 install flake8-forbidden-func==0.1.0
    - pip3 install flake8-return==1.2.0
    - pip3 install flake8-eradicate==1.5.0
    - pip3 install flake8-use-pathlib==0.3.0
    - flake8 --verbose .

black:
  stage: refactoring
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

test:
  stage: test
  image: python:3.11
  script:
    - pip3 install -r requirements/test.txt
    - cd lyceum
    - python3 manage.py test