<<<<<<< HEAD
name: CI Pipeline

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install flake8
        run: |
          pip install -r requirements/flake8.txt

      - name: Run flake8
        run: |
          flake8 --verbose .

  refactoring:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install black
        run: |
          pip install black

      - name: Run black
        run: |
          black --check .

  test:
    runs-on: ubuntu-latest
    needs: refactoring
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          pip install -r requirements/test.txt

      - name: Run tests
        run: |
          cd lyceum
          python manage.py test
=======
stages:
  [ 'linting', 'refactoring', 'test' ]

flake8:
  stage: linting
  image: registry.github.com/pipeline-components/flake8:latest
  script:
    - pip3 install -r requirements/flake8.txt
    - flake8 --verbose .

black:
  stage: refactoring
  image: registry.github.com/pipeline-components/black:latest
  script:
    - black --check .

test:
  stage: test
  image: python:3.11
  script:
    - pip3 install -r requirements/test.txt
    - cd lyceum
    - python3 manage.py test
>>>>>>> parent of eefe5de (update ci cd)
