# Generated by Django 4.2 on 2024-11-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="created_at",
            new_name="created_on",
        ),
    ]
