# Generated by Django 4.2 on 2024-11-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_rename_created_at_feedback_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Имя пользователя"
            ),
        ),
    ]
