# Generated by Django 4.2 on 2024-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_feedback_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                default=123, max_length=150, verbose_name="Имя пользователя"
            ),
            preserve_default=False,
        ),
    ]
