# Generated by Django 4.2 on 2024-11-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_alter_feedback_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "получено"),
                    ("PENDING", "в обработке"),
                    ("COMPLETE", "ответ дан"),
                ],
                default="NEW",
                max_length=8,
            ),
        ),
    ]
