# Generated by Django 4.2 on 2024-11-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_statuslog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statuslog",
            old_name="to_status",
            new_name="to",
        ),
    ]
