# Generated by Django 4.2 on 2024-11-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_rename_to_status_statuslog_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Имя пользователя"
            ),
        ),
    ]
