# Generated by Django 4.2 on 2024-11-05 17:40

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0010_feedbackfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=feedback.models.get_upload_to
            ),
        ),
    ]
