# Generated by Django 4.2 on 2024-11-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0016_alter_feedbackfile_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="text",
            field=models.TextField(default="заглушка", verbose_name="Жалоба"),
        ),
    ]
