# Generated by Django 4.2 on 2024-11-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_alter_profile_coffee_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
        ),
    ]
