# Generated by Django 4.2 on 2024-11-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("users", "0004_profile_attempt_count"),
        ("users", "0005_profile_attempt"),
        ("users", "0006_remove_profile_attempt_profile_block_time"),
        ("users", "0007_rename_attempt_count_profile_attempts_count_and_more"),
    ]

    dependencies = [
        ("users", "0003_proxyuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="block_time",
            field=models.DateTimeField(default="1111-11-11 11:11:11.1111"),
        ),
    ]
