# Generated by Django 4.2 on 2024-11-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_attempt_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attempt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
