# Generated by Django 4.2 on 2024-11-16 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_attempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="attempt",
        ),
        migrations.AddField(
            model_name="profile",
            name="block_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    11,
                    16,
                    8,
                    25,
                    17,
                    102519,
                    tzinfo=datetime.timezone.utc,
                )
            ),
            preserve_default=False,
        ),
    ]
