# Generated by Django 4.2 on 2024-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_profile_attempt_profile_block_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="attempt_count",
            new_name="attempts_count",
        ),
        migrations.AlterField(
            model_name="profile",
            name="block_time",
            field=models.DateTimeField(default="1111-11-11 11:11:11.1111"),
        ),
    ]
