# Generated by Django 4.2 on 2024-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0004_profile_attempt_count_squashed_0007_rename_attempt_count_profile_attempts_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="block_time",
            field=models.DateTimeField(null=True),
        ),
    ]
