# Generated by Django 4.2 on 2024-10-12 16:50

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        default="Название",
                        help_text="Название",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Статус публикации",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.TextField(
                        default="Слаг",
                        help_text="Слаг",
                        max_length=200,
                        validators=[
                            catalog.models.custom_validator_right_string
                        ],
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Вес",
                        validators=[catalog.models.custom_validator_zero],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        default="Название",
                        help_text="Название",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Статус публикации",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.TextField(
                        default="Слаг",
                        help_text="Слаг",
                        max_length=200,
                        validators=[
                            catalog.models.custom_validator_right_string
                        ],
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        default="Название",
                        help_text="Название",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Статус публикации",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        default="Превосходно",
                        help_text="Описание товара",
                        validators=[catalog.models.custom_validator_words],
                        verbose_name="Текст",
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="catalog.tag")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
