# Generated by Django 4.2 on 2024-10-13 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Название",
                help_text="Название",
                max_length=150,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                default="Название",
                help_text="Название",
                max_length=150,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                default="Название",
                help_text="Название",
                max_length=150,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="название",
            ),
        ),
    ]
