# Generated by Django 4.2 on 2024-10-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="main_image",
            new_name="MainImage",
        ),
    ]
