# Generated by Django 4.2 on 2024-10-12 19:28

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.TextField(
                default="Slag",
                help_text="Слаг",
                max_length=200,
                validators=[catalog.models.custom_validator_right_string],
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.TextField(
                default="Slag",
                help_text="Слаг",
                max_length=200,
                validators=[catalog.models.custom_validator_right_string],
                verbose_name="Слаг",
            ),
        ),
    ]
