# Generated by Django 4.2 on 2024-10-13 09:21

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_slug_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Статус публикации",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Название",
                help_text="Название",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="Slag",
                help_text="Слаг",
                max_length=200,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Вес",
                validators=[catalog.models.custom_validator_zero],
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Статус публикации",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                default="Название",
                help_text="Название",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                default="Превосходно",
                help_text="Описание товара",
                validators=[catalog.models.custom_validator_words],
                verbose_name="текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Статус публикации",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                default="Название",
                help_text="Название",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                default="Slag",
                help_text="Слаг",
                max_length=200,
                verbose_name="слаг",
            ),
        ),
    ]
