# Generated by Django 4.2 on 2024-10-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_normalized_name_tag_normalized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="MainImage",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="items/main_image/",
                verbose_name="Главная картинка",
            ),
        ),
        migrations.CreateModel(
            name="ItemGalery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="items/galery/",
                        verbose_name="галерея",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.item",
                    ),
                ),
            ],
        ),
    ]
