# Generated by Django 4.2 on 2024-10-26 14:26

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0004_alter_item_text"),
        ("catalog", "0005_remove_item_mainimage_mainimage"),
        ("catalog", "0006_alter_category_weight"),
    ]

    dependencies = [
        ("catalog", "0003_item_mainimage_itemgalery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                default="Превосходно",
                help_text="Описание товара",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
        migrations.RemoveField(
            model_name="item",
            name="MainImage",
        ),
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="items/main_image/",
                        verbose_name="галерея",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_image",
                        to="catalog.item",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Вес",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name="вес",
            ),
        ),
    ]
