# Generated by Django 4.2 on 2024-10-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0007_item_is_on_main"),
        ("catalog", "0008_alter_item_options"),
    ]

    dependencies = [
        (
            "catalog",
            "0004_alter_item_text_squashed_0006_alter_category_weight",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Статус показа на главной странице",
                verbose_name="на главной",
            ),
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name", "text", "id"),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
