# Generated by Django 4.2 on 2024-10-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        (
            "catalog",
            "0009_alter_category_normalized_name_alter_itemgalery_item_and_more",
        ),
        ("catalog", "0010_alter_itemgalery_item"),
        ("catalog", "0011_alter_category_normalized_name_and_more"),
        ("catalog", "0012_alter_category_normalized_name_and_more"),
    ]

    dependencies = [
        ("catalog", "0007_item_is_on_main_squashed_0008_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                default="нормализуйся",
                editable=False,
                help_text="Тут сохраняются нормализованные имена",
                max_length=150,
                verbose_name="нормализованные имена",
            ),
        ),
        migrations.AlterField(
            model_name="itemgalery",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                default="нормализуйся",
                editable=False,
                help_text="Тут сохраняются нормализованные имена",
                max_length=150,
                verbose_name="нормализованные имена",
            ),
        ),
        migrations.AlterField(
            model_name="itemgalery",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                default="нормализуйся",
                editable=False,
                help_text="Тут сохраняются нормализованные имена",
                max_length=150,
                unique=True,
                verbose_name="нормализованные имена",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                default="нормализуйся",
                editable=False,
                help_text="Тут сохраняются нормализованные имена",
                max_length=150,
                unique=True,
                verbose_name="нормализованные имена",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                default="нормализуйся",
                editable=False,
                help_text="Тут сохраняются нормализованные имена",
                max_length=150,
                verbose_name="нормализованные имена",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                default="нормализуйся",
                editable=False,
                help_text="Тут сохраняются нормализованные имена",
                max_length=150,
                verbose_name="нормализованные имена",
            ),
        ),
    ]
