# Generated by Django 4.2 on 2024-10-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0009_alter_category_normalized_name_alter_itemgalery_item_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemgalery",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to="catalog.item",
            ),
        ),
    ]
