# Generated by Django 4.2 on 2024-10-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_itemgalery_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                default="нормализуйся",
                editable=False,
                help_text="Тут сохраняются нормализованные имена",
                max_length=150,
                unique=True,
                verbose_name="нормализованные имена",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                default="нормализуйся",
                editable=False,
                help_text="Тут сохраняются нормализованные имена",
                max_length=150,
                unique=True,
                verbose_name="нормализованные имена",
            ),
        ),
    ]
