# Generated by Django 4.2 on 2024-10-28 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0009_alter_category_normalized_name_alter_itemgalery_item_and_more_squashed_0012_alter_category_normalized_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date_last",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="item",
            name="date_start",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
