# Generated by Django 4.2 on 2024-10-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0013_item_date_last_item_date_start"),
        ("catalog", "0014_alter_item_date_last_alter_item_date_start"),
        ("catalog", "0015_rename_date_start_item_created_at_and_more"),
    ]

    dependencies = [
        (
            "catalog",
            "0009_alter_category_normalized_name_alter_itemgalery_item_and_more_squashed_0012_alter_category_normalized_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
