# Generated by Django 4.2 on 2024-10-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_item_date_last_item_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="date_last",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="date_start",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
