# Generated by Django 4.2 on 2024-10-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_item_date_last_alter_item_date_start"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="date_start",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="date_last",
            new_name="updated_at",
        ),
    ]
