name: CI Pipeline

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install flake8
        run: |
          pip install -r requirements/flake8.txt

      - name: Run flake8
        run: |
          flake8 --verbose .

  refactoring:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install black
        run: |
          pip install black

      - name: Run black
        run: |
          black --check .

  test:
    runs-on: ubuntu-latest
    needs: refactoring
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          pip install -r requirements/test.txt

      - name: Run tests
        run: |
          cd lyceum
          python manage.py test